[package]
name = "templr"
version = "0.1.0"
license = "Apache-2.0"
workspace = ".."
readme = "../README.md"
edition = "2021"

[dependencies]
templr_macros = { path = "../templr_macros" }
anyhow = "1.0"
askama_escape = "0.10"
